name: Generate snake animation

on:
  schedule: # executa a cada 12 horas
    - cron: "0 */12 * * *" # Executa às 00:00 e 12:00 UTC
  workflow_dispatch: # Permite execução manual
  push: # Executa ao fazer push na branch master
    branches:
      - master

jobs:
  generate:
    permissions:
      contents: write # Permissão necessária para push de arquivos
    runs-on: ubuntu-latest
    timeout-minutes: 10 # Tempo limite estendido para evitar problemas de timeout

    steps:
      # Clonar o repositório
      - name: Checkout repository
        uses: actions/checkout@v3

      # Gerar o arquivo snake.svg
      - name: Generate snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: dist/snake.svg?palette=github-dark

      # Fazer push do arquivo gerado
      - name: Push snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output # Alvo do branch para saída
          build_dir: dist # Diretório onde o snake.svg foi gerado
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
